[features]
seeds = false
skip-lint = false

[programs.localnet]
prediction_pump = "2vi9hVuYBws8GwFqPG6eRQRFoEMGfkCny2Lbvf3pFuzu"

[programs.devnet]
prediction_pump = "2vi9hVuYBws8GwFqPG6eRQRFoEMGfkCny2Lbvf3pFuzu"

[programs.mainnet]
prediction_pump = "2vi9hVuYBws8GwFqPG6eRQRFoEMGfkCny2Lbvf3pFuzu"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program = "metadata.so"

[test.validator]
url = "https://api.devnet.solana.com"

[build]
exclude = ["node_modules", "target", ".git"]