version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: prediction-pump-postgres
    environment:
      POSTGRES_DB: prediction_pump
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/migrations:/docker-entrypoint-initdb.d
    networks:
      - prediction-pump-network

  redis:
    image: redis:7-alpine
    container_name: prediction-pump-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - prediction-pump-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: prediction-pump-backend
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/prediction_pump
      - REDIS_URL=redis://redis:6379
      - PORT=3001
    ports:
      - "3001:3001"
    depends_on:
      - postgres
      - redis
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - prediction-pump-network
    command: npm run dev

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: prediction-pump-frontend
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:3001
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - prediction-pump-network
    command: npm run dev

volumes:
  postgres_data:
  redis_data:

networks:
  prediction-pump-network:
    driver: bridge